### ISSUE TITLE
Upload Wizard -- Theme selection

### ISSUE THREAD

**Issue by georg23** [magnolo/aot#14]
Minor thing:
If I select a first level theme (e.g. Commitee against torture), all subcategories are selected (perfect). But then, I cannot de-select the subcategories, unless I de-select the first - level category (Commitee against torture)
![theme-subcats](https://cloud.githubusercontent.com/assets/18422620/17850581/26696b4c-685e-11e6-99a8-09732464b94f.png)

**Comment by magnolo** [comment]
Thats not that easy... needs more investigation. It is just a prototype of new nested select so the hirarchy is visible.

**Comment by georg23** [comment]
Ok then, let's leave it for now. The important thing is, that the nested items are visible -- therefore, ok!
